### ISSUE TITLE
dependency failed to start: container supabase-analytics is unhealthy

### ISSUE THREAD

**Issue by GlauberF** [Superflows-AI/superflows#284]
I'm trying to run the local development environment with docker, following the steps in the readme, but the "supabase-analytics" container doesn't start.

```
[+] Building 826.7s (13/13) FINISHED                                                                                          docker:default
 => [superflows internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 545B                                                                                                    0.0s
 => WARN: FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "linux/amd64" (line 4)                    0.0s
 => [superflows internal] load metadata for docker.io/library/node:alpine                                                               2.3s
 => [superflows internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 58B                                                                                                        0.0s
 => [superflows internal] load build context                                                                                            0.3s
 => => transferring context: 68.36MB                                                                                                    0.3s
 => [superflows 1/7] FROM docker.io/library/node:alpine@sha256:1467ea23cce893347696b155b9e00e7f0ac7d21555eb6f27236f1328212e045e        17.9s
 => => resolve docker.io/library/node:alpine@sha256:1467ea23cce893347696b155b9e00e7f0ac7d21555eb6f27236f1328212e045e                    0.0s
 => => sha256:7a291b8a7b575b411b08e82b066a02d5d73db2377f324d619e07141f3169937c 1.39MB / 1.39MB                                          4.1s
 => => sha256:1467ea23cce893347696b155b9e00e7f0ac7d21555eb6f27236f1328212e045e 6.41kB / 6.41kB                                          0.0s
 => => sha256:db7d4c706c493243e556c19cf3b80556f8dc91d69fcb750b16909624bd5cbfa1 1.72kB / 1.72kB                                          0.0s
 => => sha256:bd8023897f3875f1759c7b6704a1c7ee793e5c6fbc35b3b680279476ed84bdc8 6.19kB / 6.19kB                                          0.0s
 => => sha256:43c4264eed91be63b206e17d93e75256a6097070ce643c5e8f0379998b44f170 3.62MB / 3.62MB                                          3.9s
 => => sha256:453ca8c35a6710c3a236b7f3e68f3688ef04449b59a2b80ad92abc69b7c4c718 50.85MB / 50.85MB                                       16.5s
 => => extracting sha256:43c4264eed91be63b206e17d93e75256a6097070ce643c5e8f0379998b44f170                                               0.0s
 => => sha256:15929fe50b42a226c1ffcbf061b9446ceefb6fc7ae3201e53aaaf6109b719d46 445B / 445B                                              4.2s
 => => extracting sha256:453ca8c35a6710c3a236b7f3e68f3688ef04449b59a2b80ad92abc69b7c4c718                                               1.0s
 => => extracting sha256:7a291b8a7b575b411b08e82b066a02d5d73db2377f324d619e07141f3169937c                                               0.0s
 => => extracting sha256:15929fe50b42a226c1ffcbf061b9446ceefb6fc7ae3201e53aaaf6109b719d46                                               0.0s
 => [superflows 2/7] RUN mkdir -p /app                                                                                                  0.7s
 => [superflows 3/7] WORKDIR /app                                                                                                       0.1s
 => [superflows 4/7] COPY package.json ./                                                                                               0.0s
 => [superflows 5/7] RUN npm i && npm cache clean --force                                                                             632.5s
 => [superflows 6/7] COPY . /app                                                                                                        2.4s 
 => [superflows 7/7] RUN rm -f .env                                                                                                     0.3s 
 => [superflows] exporting to image                                                                                                   170.2s 
 => => exporting layers                                                                                                               170.1s 
 => => writing image sha256:ea9ce2862a36de2660873b9d9eb4cdde255d0f0c4906760979653e17c3d30844                                            0.0s 
 => => naming to docker.io/library/development-superflows                                                                               0.0s 
 => [superflows] resolving provenance for metadata file                                                                                 0.0s
[+] Running 15/15
 ✔ Network development_default               Created                                                                                    0.2s 
 ✔ Container supabase-imgproxy               Started                                                                                  207.8s 
 ✔ Container supabase-vector                 Healthy                                                                                  213.3s 
 ✔ Container supabase-db                     Healthy                                                                                  219.9s 
 ✘ Container supabase-analytics              Error                                                                                    253.1s 
 ✔ Container supabase-meta                   Created                                                                                    0.1s 
 ✔ Container realtime-dev.supabase-realtime  Created                                                                                    0.1s 
 ✔ Container supabase-kong                   Created                                                                                    0.1s 
 ✔ Container supabase-rest                   Created                                                                                    0.1s 
 ✔ Container supabase-auth                   Created                                                                                    0.1s 
 ✔ Container supabase-edge-functions         Created                                                                                    0.1s 
 ✔ Container supabase-pooler                 Created                                                                                    0.1s 
 ✔ Container supabase-studio                 Created                                                                                    0.1s 
 ✔ Container superflows                      Created                                                                                  207.0s 
 ✔ Container supabase-storage                Created                                                                                    0.0s 
dependency failed to start: container supabase-analytics is unhealthy
```
**Log**
```
sudo docker logs supabase-analytics
[sudo] senha para asaas: 
LOGFLARE_NODE_HOST is: 127.0.0.1

14:12:18.452 [info] Starting migration

14:12:19.005 [error] Postgrex.Protocol (#PID<0.163.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "supabase_admin"

14:12:19.005 [error] Postgrex.Protocol (#PID<0.162.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "supabase_admin"

14:12:20.837 [error] Postgrex.Protocol (#PID<0.163.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "supabase_admin"

14:12:20.890 [error] Postgrex.Protocol (#PID<0.162.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "supabase_admin"

14:12:23.192 [error] Postgrex.Protocol (#PID<0.162.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "supabase_admin"

14:12:24.514 [error] Postgrex.Protocol (#PID<0.163.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "supabase_admin"

14:12:27.029 [error] Postgrex.Protocol (#PID<0.162.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "supabase_admin"

14:12:29.900 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:

    config :logflare, Logflare.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 10950ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:738: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:552: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)

14:12:33.501 [notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
```

**Comment by rituraj-yactraq** [comment]
https://github.com/orgs/supabase/discussions/20211

**Comment by rituraj-yactraq** [comment]
I would recommend not to use the docker build method and instead the npx supabase method

**Comment by GlauberF** [comment]
@rituraj-yactraq Would you have a script of the steps, as per your suggestion, to run in development mode?

**Comment by rituraj-yactraq** [comment]
@GlauberF 
npm i
npm install supabase --save-dev
npx supabase start

This will create supabase local instance and start superflows dashboard. You should join the superflows slack channel, common installation issues solution you will find there.

**Comment by GlauberF** [comment]
@rituraj-yactraq Thanks

**Comment by GlauberF** [comment]
@rituraj-yactraq When trying to run the `npm i` command, I get the error below.
![Captura de tela de 2024-11-22 10-41-44](https://github.com/user-attachments/assets/950b7e84-eefe-4c2c-91f3-b912e781ddbd)
